name: Ansible Lint

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "ansible/**"
  pull_request:
    branches: [main]
    paths:
      - "ansible/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@a3fc7e4def4c3576a221fd1e0e58c0ee43f73af5  # v24.2.0
        with:
          path: ansible/
