name: Ansible Lint

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "ansible/**"
  pull_request:
    branches: [main]
    paths:
      - "ansible/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.2.0
        with:
          path: ansible/
